groups:
  - name: multi-agent-alerts
    interval: 30s
    rules:
      # Application alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      - alert: AgentUnhealthy
        expr: agent_health_status != 1
        for: 5m
        labels:
          severity: critical
          team: ai
        annotations:
          summary: "Agent {{ $labels.agent_id }} is unhealthy"
          description: "Agent {{ $labels.agent_id }} of type {{ $labels.agent_type }} has been unhealthy for 5 minutes"

      - alert: HighSessionQueueDepth
        expr: session_queue_depth > 50
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High session queue depth"
          description: "Session queue depth is {{ $value }}"

      - alert: LowCustomerSatisfaction
        expr: avg_over_time(customer_satisfaction_score[1h]) < 7
        for: 30m
        labels:
          severity: warning
          team: customer_success
        annotations:
          summary: "Low customer satisfaction score"
          description: "Average satisfaction score is {{ $value }} over the last hour"

      # Infrastructure alerts
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High memory usage for {{ $labels.pod }}"
          description: "Memory usage is {{ $value | humanizePercentage }} for pod {{ $labels.pod }}"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.9
        for: 10m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High CPU usage for {{ $labels.pod }}"
          description: "CPU usage is {{ $value | humanizePercentage }} for pod {{ $labels.pod }}"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} is down"

      - alert: PostgresDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance {{ $labels.instance }} is down"

      # Business alerts
      - alert: HighEscalationRate
        expr: rate(session_escalations_total[1h]) / rate(sessions_total[1h]) > 0.3
        for: 30m
        labels:
          severity: warning
          team: customer_success
        annotations:
          summary: "High escalation rate"
          description: "Escalation rate is {{ $value | humanizePercentage }} over the last hour"

      - alert: LowResolutionRate
        expr: rate(sessions_resolved_total[1h]) / rate(sessions_total[1h]) < 0.7
        for: 30m
        labels:
          severity: warning
          team: customer_success
        annotations:
          summary: "Low resolution rate"
          description: "Resolution rate is {{ $value | humanizePercentage }} over the last hour"