apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-agent-config
  namespace: customer-service
data:
  APP_NAME: "multi-agent-customer-service"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_PREFIX: "/api/v1"
  VERTEX_AI_LOCATION: "us-central1"
  VERTEX_AI_MODEL: "gemini-1.5-pro"
  MAX_OUTPUT_TOKENS: "2048"
  TOP_P: "0.95"
  SESSION_TIMEOUT_MINUTES: "30"
  MAX_SESSIONS_PER_AGENT: "10"
  SESSION_CLEANUP_INTERVAL_MINUTES: "5"
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  ENABLE_TRACING: "true"
  ENABLE_DEMO_MODE: "false"
  ENABLE_AGENT_ANALYTICS: "true"
  ENABLE_SESSION_RECORDING: "true"