apiVersion: v1
kind: Service
metadata:
  name: multi-agent-service
  namespace: customer-service
  labels:
    app: multi-agent-cs
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: multi-agent-cs
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: multi-agent-external
  namespace: customer-service
  labels:
    app: multi-agent-cs
    component: api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: multi-agent-cs
    component: api